# Generated by Django 3.2.15 on 2022-09-07 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_report',
            fields=[
                ('Hemoglobin', models.FloatField(blank=True, null=True)),
                ('RBC', models.FloatField(blank=True, null=True)),
                ('WBC', models.FloatField(blank=True, null=True)),
                ('Platelets', models.FloatField(blank=True, null=True)),
                ('ESR', models.FloatField(blank=True, null=True)),
                ('Neutrophil', models.FloatField(blank=True, null=True)),
                ('Lymphocyte', models.FloatField(blank=True, null=True)),
                ('MCV', models.FloatField(blank=True, null=True)),
                ('MCH', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('blood_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
