# Generated by Django 3.2.15 on 2022-09-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_report',
            old_name='ESR',
            new_name='esr',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='Hemoglobin',
            new_name='hemoglobin',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='Lymphocyte',
            new_name='lymphocyte',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='MCH',
            new_name='mch',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='MCV',
            new_name='mcv',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='Neutrophil',
            new_name='neutrophil',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='Platelets',
            new_name='platelets',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='RBC',
            new_name='rbc',
        ),
        migrations.RenameField(
            model_name='blood_report',
            old_name='WBC',
            new_name='wbc',
        ),
    ]
