# Generated by Django 3.2.15 on 2022-09-12 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
        ('medical_report', '0002_auto_20220909_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='True', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='blood/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
